# Generated by Django 2.0.3 on 2018-09-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test01', '0003_auto_20180926_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='difinition',
            name='kana',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
